version: 7.0.{build}-alpha
configuration: Release

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master
  # blacklist
  except:
    - gh-pages

skip_tags: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: 7.0.0.0
  assembly_file_version: 7.0.{build}
  assembly_informational_version: '{version}'

nuget:
  project_feed: true
  disable_publish_on_pr: true

install:
  - ps: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1" -OutFile "dotnet-install.ps1"
  - ps: .\dotnet-install.ps1 -Version 1.0.0
  - ps: Import-Module .\Set-Version.psm1
  - ps: Set-Version -CsprojPattern "src/*/*.csproj" -Version $env:APPVEYOR_BUILD_VERSION

before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore --verbosity Minimal

build_script:
  - cmd: dotnet build --configuration %CONFIGURATION%

after_build:
  - cmd: dotnet pack src\Paramore.Brighter --configuration %CONFIGURATION% --no-build --output ..\..\nupkgs
  - cmd: dotnet pack src\Paramore.Brighter.ServiceActivator --configuration %CONFIGURATION% --no-build --output ..\..\nupkgs 
  - cmd: dotnet pack src\Paramore.Brighter.CommandStore.MsSql --configuration %CONFIGURATION% --no-build --output ..\..\nupkgs
  - cmd: dotnet pack src\Paramore.Brighter.CommandStore.Sqlite --configuration %CONFIGURATION% --no-build --output ..\..\nupkgs
  - cmd: dotnet pack src\Paramore.Brighter.MessageStore.EventStore --configuration %CONFIGURATION% --no-build --output ..\..\nupkgs
  - cmd: dotnet pack src\Paramore.Brighter.MessageStore.MsSql --configuration %CONFIGURATION% --no-build --output ..\..\nupkgs
  - cmd: dotnet pack src\Paramore.Brighter.MessageStore.Sqlite --configuration %CONFIGURATION% --no-build --output ..\..\nupkgs
  - cmd: dotnet pack src\Paramore.Brighter.MessagingGateway.AWSSQS --configuration %CONFIGURATION% --no-build --output ..\..\nupkgs
  - cmd: dotnet pack src\Paramore.Brighter.MessagingGateway.AzureServiceBus --configuration %CONFIGURATION% --no-build --output ..\..\nupkgs
  - cmd: dotnet pack src\Paramore.Brighter.MessagingGateway.RESTMS --configuration %CONFIGURATION% --no-build --output ..\..\nupkgs
  - cmd: dotnet pack src\Paramore.Brighter.MessagingGateway.RMQ --configuration %CONFIGURATION% --no-build --output ..\..\nupkgs

test_script:
  - cmd: dotnet test tests\Paramore.Brighter.Tests\Paramore.Brighter.Tests.csproj --filter "Category!=MSSQL & Category!=RMQ & Category!=AWS & Category != RESTMS"

artifacts:
  - path: nupkgs\*.nupkg

cache:
- '%USERPROFILE%\.nuget\packages'

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/f67b9440940cca246ec4q
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true