version: 8.0.{build}
image: Ubuntu1804
configuration: Release
stack: jdk 11

branches:
  only:
  - master
  - testappveyor
  # blacklist
  except:
    - gh-pages

skip_commits:
  files:
    - '**/*.md'

skip_tags: true

dotnet_csproj:
  patch: true
  file: '**\*.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '8.0.0.0'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  Sql__TestsBrighterConnectionString: Server=localhost;Database=BrighterTests;User ID=sa;Password=Password123!;Application Name=BrighterTests
  Sql__TestsMasterConnectionString: Server=localhost;Database=master;User ID=sa;Password=Password123!;Application Name=BrighterTests
install:
- sh: >-
    sudo snap install docker

    docker-compose up -d

    java --version

    docker ps
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
before_test:
- sh: >-
    docker ps
 
    curl http://localhost:8000/shell/
test:
  categories:
    except:
    - AWS
    - RESTMS
    - Kafka

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/c3a7c308c675e3e655d0
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
    