version: 2.0.{build}
image: Visual Studio 2017
configuration: Release

dotnet_csproj:
  patch: true
  file: 'Directory.Build.Props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '1.0.0.0'
  file_version: '{version}'
  informational_version: '{version}'

build_script:
  - cmd: dotnet build . --configuration Release

test_script:
  - cmd: dotnet test tests\tests.csproj --configuration Release 

artifacts:
  - path: '**\*.nupkg'

deploy: off
