version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

dotnet_csproj:
  patch: true
  file: 'Directory.Build.Props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '1.0.0.0'
  file_version: '{version}'
  informational_version: '{version}'

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

test: 

artifacts:
  - path: '**\*.nupkg'

deploy: off
