version: 7.0.{build}-beta
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
  # blacklist
  except:
    - gh-pages
skip_tags: true
configuration: 
#- Debug
- Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: 7.0.0.0
  assembly_file_version: 7.0.{build}
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
  disable_publish_on_pr: true
before_build:
  - cmd: dotnet --info
  - cmd: cd Brighter
  - cmd: dotnet restore -v Minimal
  - ps: >-
        Get-ChildItem . -Recurse -Include project.json | ForEach-Object {
          (Get-Content $PSItem) -Replace """version"": ""1.0.0-*""", """version"": ""$($env:APPVEYOR_BUILD_VERSION)""" | Set-Content -Path $PSItem;
          }

build_script:
  - cmd: dotnet build -c Release */**/project.json

after_build:
  - cmd: dotnet pack paramore.brighter.commandprocessor/project.json --configuration Release --no-build --output nupkgs
  - cmd: dotnet pack paramore.brighter.serviceactivator/project.json --configuration Release --no-build --output nupkgs 
  - cmd: dotnet pack paramore.brighter.commandprocessor.messaginggateway.rmq/project.json --configuration Release --no-build --output nupkgs

test_script:
  - cmd: dotnet test paramore.brighter.commandprocessor.tests.nunit/project.json --where "cat!=MSSQL && cat!=EventStore && cat!=AWS && cat!=RESTMS && cat!=RMQ" --result=brightertestresults.xml
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\brightertestresults.xml))
  - cmd: dotnet test paramore.brighter.commandprocessor.viewer.tests/project.json --where "cat!=MSSQL && cat!=EventStore && cat!=AWS && cat!=RESTMS && cat!=RMQ" --result=viewertestresults.xml
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\viewertestresults.xml))
  - cmd: dotnet test Examples/TasksTests/project.json --where "cat!=MSSQL && cat!=EventStore && cat!=AWS && cat!=RESTMS && cat!=RMQ" --result=tasktestresults.xml
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tasktestresults.xml))

artifacts:
  # pushing all *.nupkg files in build directory recursively
  - path: '/**/nupkgs/*.nupkg'

cache:
- '%USERPROFILE%\.nuget\packages'

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/182838afa865c8e16f72
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true