# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: sudo service mysql stop
  displayName: service mysql stop

- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'

- task: DockerCompose@0
  displayName: Run services for tests
  inputs:
    containerregistrytype: 'Azure Container Registry'
    dockerComposeFile: 'docker-compose.yaml'
    action: 'Run services'


- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    arguments: '-v normal --configuration $(buildConfiguration) --no-build --logger trx --filter "Category!=AWS&Category!=RESTMS"'
    testRunTitle: 'dotnet test $(buildConfiguration)'

- task: PublishTestResults@2
  displayName: Publish Test Results
  condition: succeededOrFailed()
  inputs:
    testRunTitle: "Ubuntu (dotnet core 2.1)"
    platform: "Ubuntu"
    testRunner: VSTest
    testResultsFiles: '**/*.trx'





  


