name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  # Project name to pack and publish
  # GitHub Packages Feed settings
  GITHUB_FEED: https://nuget.pkg.github.com/
  GITHUB_USER: iancooper
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore 
      - uses: actions/upload-artifact@v2
        with:
          name: dotnet artifacts
          path: |
            ./
            src/
            tests/
  
  test:

    runs-on: ubuntu-latest
    needs: [build]

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dotnet artifacts
      - name: Core Tests
        run: dotnet test ./tests/Paramore.Brighter.Core.Tests/Paramore.Brighter.Core.Tests.csproj --configuration Release --no-build

  package:
    
    runs-on: ubuntu-latest
    needs: [test]
    
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dotnet artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: nuget packages
          path: "**/*.nupkg"
      
  prerelease:
    runs-on: ubuntu-latest
    needs: [package]
    
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: nuget packages
      - name: Push to GitHub Feed
        run: |
          for f in **/*.nupkg
          do
            curl -vX PUT -u "$GITHUB_USER:$GITHUB_TOKEN" -F package=@$f $GITHUB_FEED$GITHUB_REPOSITORY
          done
    
  redis-ci:
    runs-on: ubuntu-latest
    needs: [test]
    
    services:
      redis:  
        image: redis:latest
        ports:
        - 6379/tcp
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5             
      
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dotnet artifacts
      - name: Install Info
        run: |  
           echo "Root Directory"
           ls -l .
           echo "Tests Directory"
           ls -l tests/
           echo "Tests Directory"
           ls -l tests/Paramore.Brighter.Redis.Tests
      - name: Redis Transport Tests
        run: dotnet test ./tests/Paramore.Brighter.Redis.Tests/Paramore.Brighter.Redis.Tests.csproj --configuration Release --no-build
  
  rabbitmq-ci:
    runs-on: ubuntu-latest
    needs: [test]

    services:
      rabbitmq:
        image: rabbitmq:latest
        ports:
        - 5672/tcp
        # needed because the rabbitmq container does not provide a healthcheck
        options: >-
          --health-cmd "rabbitmqctl node_health_check"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Echo RABBITMQ_PORT
        run: echo "$RABBITMQ_PORT"
        env:
          # get randomly assigned published ports
          RABBITMQ_PORT: ${{ job.services.rabbitmq.ports[5672] }}
      - uses: actions/download-artifact@v2
        with:
          name: dotnet artifacts
      - name: Redis Transport Tests
        run: dotnet test ./tests/Paramore.Brighter.RMQ.Tests/Paramore.Brighter.RMQ.Tests.csproj --configuration Release --no-build



